<nav>
    <a style="color: #072c8be5; margin-right: 10px; font-size: 24px;"  href="<?=BASE_URL?>">Главная</a>
    <a style="color: #072c8be5;  margin-right: 10px; font-size: 24px;" href="<?=BASE_URL?>?page=posts">Посты</a>
    <a style="color: #072c8be5;  margin-right: 10px; font-size: 24px;" href="<?=BASE_URL?>?page=categories">Категории</a>
    <a style="color: #072c8be5;  margin-right: 10px; font-size: 24px;" href="<?=BASE_URL?>?page=calc">Калькулятор</a>
    <a style="color: #072c8be5;  margin-right: 10px; font-size: 24px;" href="<?=BASE_URL?>?page=about">О блоге</a>
</nav><br><br>
